# Copyright 2025-     FlagOS Contributors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: NV3.6-Qwen-Benchmark

on:
  push:
    branches: [ "main", "triton_v3.6.x" ]
  pull_request:
    branches: [ "main", "triton_v3.6.x" ]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  nv36x-qwen:
    runs-on: nvidia3.6-qwen
    if: ${{ github.repository == 'flagos-ai/flagtree' && github.event.pull_request.draft == false }}
    steps:
      - name: Setup environment
        shell: bash
        run: |
          source ~/env.sh
          env | grep -E '^(http_proxy|https_proxy|all_proxy|no_proxy)=' >> $GITHUB_ENV || true

      - name: Smart Checkout
        uses: flagos-ai/FlagTree/.github/actions/smart-checkout@main
        with:
          checkout_version: 'v6'

      - name: Check if backend-relevant files changed
        id: check_backend
        uses: flagos-ai/FlagTree/.github/actions/check-backend-changed@main
        with:
          backend: nvidia

      - name: Cleanup FlagTree Environment
        if: ${{ steps.check_backend.outputs.should_skip != 'true' }}
        uses: flagos-ai/FlagTree/.github/actions/cleanup-flagtree-env@main

      - name: Build FlagTree
        if: ${{ steps.check_backend.outputs.should_skip != 'true' }}
        shell: bash
        run: |
          set -x
          source ~/env-3.6.sh
          # export FLAGCX_RECOMPILE=ON
          # export USE_FLAGCX=ON
          MAX_JOBS=32 python3 -m pip install . --no-build-isolation -v

      - name: Clear cache if ClearCache label present
        if: steps.check_backend.outputs.should_skip != 'true'
        id: clear_cache
        uses: flagos-ai/FlagTree/.github/actions/clear-cache-if-labeled@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          backend: nvidia-qwen

      - name: Start the service
        if: ${{ steps.check_backend.outputs.should_skip != 'true' }}
        shell: bash
        run: |
          export BENCH_SCRIPT_DIR="${PWD}/.github/workflows/benchmark/nvidia/nv3.6-qwen3.6"
          env | grep -E '^(BENCH_SCRIPT_DIR)=' >> $GITHUB_ENV || true
          cd ~/flagrelease
          bash ${BENCH_SCRIPT_DIR}/start.sh

      - name: Show the baseline
        if: ${{ steps.check_backend.outputs.should_skip != 'true' }}
        shell: bash
        run: |
          cd ~/flagrelease
          cat ${BENCH_SCRIPT_DIR}/ref.txt

      - name: Run the benchmark
        if: ${{ steps.check_backend.outputs.should_skip != 'true' }}
        shell: bash
        run: |
          set -x
          cd ~/flagrelease
          bash ${BENCH_SCRIPT_DIR}/perf.sh

      - name: Stop the service
        if: ${{ steps.check_backend.outputs.should_skip != 'true' }}
        shell: bash
        run: |
          cd ~/flagrelease
          bash ${BENCH_SCRIPT_DIR}/stop.sh
