# Copyright 2025-     FlagOS Contributors
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: CD-Ppu3.6

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      WHL_VER:
        description: '0.6.0.dev1 < 0.6.0a1 < 0.6.0b1 < 0.6.0rc1 < 0.6.0 < 0.6.0.post1'
        required: true
        default: '0.6.0'
      PYTHON_VER:
        required: true
        default: '3.12'
      PLATFORM:
        required: true
        default: 'x86_64'
      BRANCH:
        required: true
        default: 'main'
      TRITON:
        required: true
        default: '3.6'
      BACKEND:
        required: true
        default: 'ppu'
      FLAGTREE_PYPI_KEY:
        required: false
  workflow_call:
    inputs:
      WHL_VER:
        type: string
        required: true
        default: '0.6.0'
      PYTHON_VER:
        type: string
        required: true
        default: '3.12'
      PLATFORM:
        type: string
        required: true
        default: 'x86_64'
      BRANCH:
        type: string
        required: true
        default: 'main'
      TRITON:
        type: string
        required: true
        default: '3.6'
      BACKEND:
        type: string
        required: true
        default: 'ppu'
      FLAGTREE_PYPI_KEY:
        type: string
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ inputs.WHL_VER }}-${{ inputs.PYTHON_VER }}-${{ inputs.PLATFORM }}
  cancel-in-progress: true

jobs:
  delivery:
    runs-on: ppu3.6-cd
    if: ${{ github.repository == 'FlagTree/flagtree' || github.repository == 'flagos-ai/flagtree' }}
    steps:
      - name: Check branch
        shell: bash
        run: |
          TARGET_BRANCH="${{ github.ref_name }}"
          if [[ ! "$TARGET_BRANCH" =~ ^(${{ inputs.BRANCH }})$ ]]; then
            echo "❌ This workflow must be run from branch '${{ inputs.BRANCH }}', but got '${TARGET_BRANCH}'"
            exit 1
          fi
          echo "TARGET_BRANCH=$TARGET_BRANCH" >> $GITHUB_ENV
          echo "✅ Branch check passed: ${TARGET_BRANCH}"

      - name: Setup environment
        shell: bash
        run: |
          source ~/env.sh
          env | grep -E '^(http_proxy|https_proxy|all_proxy|no_proxy)=' >> $GITHUB_ENV || true

      - name: Smart Checkout
        uses: flagos-ai/FlagTree/.github/actions/smart-checkout@main
        with:
          checkout_version: 'v6'

      - name: FlagTree bdist_wheel
        if: ${{ env.TARGET_BRANCH == inputs.BRANCH }}
        shell: bash
        run: |
          set -x
          CHIP=""
          TRITON_VER=${{ inputs.TRITON }}
          export FLAGTREE_BACKEND=${{ inputs.BACKEND }}
          WHL_VER=${{ inputs.WHL_VER }}
          PYTHON_VER=${{ inputs.PYTHON_VER }}
          export FLAGTREE_WHEEL_VERSION="${WHL_VER}+${FLAGTREE_BACKEND}${CHIP}${TRITON_VER}"

          RES="--index-url=https://resource.flagos.net/repository/flagos-pypi-hosted/simple"
          if python${PYTHON_VER} -m pip download --no-deps "flagtree===${FLAGTREE_WHEEL_VERSION}" -d . $RES >/dev/null 2>&1; then
            echo "❌ flagtree===${FLAGTREE_WHEEL_VERSION} already exists!"
            exit 1
          else
            echo "✅ flagtree===${FLAGTREE_WHEEL_VERSION} does not exist, proceed to build"
          fi

          rm -rf ./build ./*.egg-info
          { export FLAGTREE_PYPI_KEY=${{ inputs.FLAGTREE_PYPI_KEY }}; } 2>/dev/null
          # export TRITON_APPEND_CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release"
          MAX_JOBS=32 python${PYTHON_VER} setup.py bdist_wheel -d ~/dist-flagtree
          env | grep -E '^(FLAGTREE_WHEEL_VERSION)=' >> $GITHUB_ENV || true

      - name: FlagTree push tag
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -x
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          TAG="${FLAGTREE_WHEEL_VERSION}"
          git config user.name "flagtree-bot"
          git config user.email "flagtree_ai@163.com"
          if git rev-parse "${TAG}" >/dev/null 2>&1; then
            echo "⚠️ Tag '${TAG}' already exists, force moving to current commit"
            git tag -f -a "${TAG}" -m "pypi ${TAG}"
          else
            git tag -a "${TAG}" -m "pypi ${TAG}"
          fi
          MAX_RETRY=100
          RETRY_INTERVAL=10
          success=false
          for i in $(seq 1 $MAX_RETRY); do
            echo "Attempt ${i}/${MAX_RETRY}:"
            if git push --force origin "${TAG}"; then
              success=true
              break
            fi
            echo "Push failed, retrying in ${RETRY_INTERVAL}s..."
            sleep $RETRY_INTERVAL
          done
          if [ "$success" != "true" ]; then
            echo "git push failed after $MAX_RETRY attempts"
            exit 1
          fi

      - name: FlagTree upload whl
        shell: bash
        run: |
          set -x
          PLATFORM=${{ inputs.PLATFORM }}
          PYTHON_VER=${{ inputs.PYTHON_VER }}
          CP_VER=$(printf '%s' "$PYTHON_VER" | tr -d '.')
          FLAGTREE_WHL="flagtree-${FLAGTREE_WHEEL_VERSION}-cp${CP_VER}-cp${CP_VER}-linux_${PLATFORM}.whl"
          pushd ~/dist-flagtree
          twine check ${FLAGTREE_WHL}
          echo "Upload ${FLAGTREE_WHL}"
          bash upload_flagtree_whl.sh "${FLAGTREE_WHL}"
          popd
